<?php
$banner = $this->getBanner();
?>
<?php if($banner): ?>
<div class="add_section">
	<div class="container">
		<?php if($banner->getImageUrl()): ?><img class="dsktop_only" src="<?php echo $banner->getImageUrl(); ?>"><?php endif; ?>
		<?php if($banner->getMobileImageUrl()): ?><img class="mobile_only" src="<?php echo $banner->getMobileImageUrl(); ?>"><?php endif; ?>
	</div>
</div>
<?php endif; ?>