<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = false;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
	
	$helper = $this->helper('Cluedy\Mhlatk\Helper\Data');
?>
<div class="product_list_home best_seller">
	<div class="container">
        <?php if ($block->getTitle()): ?>
        <h3><?= $block->escapeHtml(__($block->getTitle())) ?></h3>
        <?php endif ?>
        <div class="block-content">
            <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
            <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
                <ul class="best_elec_slider">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
					<?php 
						$isNew = $helper->isNew($_item);
						$isSpecial = $helper->isSpecial($_item); 
					?>
                        <li class="<?php if($isNew){ echo 'new_arrival'; } if($isSpecial){ echo ' slash_sale'; } ?>">
                            <div class="product_list_wrap">
								<figure>
									<a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
										<?= $block->getImage($_item, $image)->toHtml() ?>
									</a>
								</figure>
                                <figcaption class="product-item-name">
                                    <h5>
										<a title="<?= $block->escapeHtml($_item->getName()) ?>"
										   href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
										   class="product-item-link">
											<?= $block->escapeHtml($_item->getName()) ?>
										</a>
									</h5>
                                
									<div class="product_price">
										<?php echo $block->getProductPriceHtml($_item, $type); ?>
										<?php if ($showCart): ?>
											<a class="mob_addtocart" href="javascript:;" data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"></a>
										<?php endif; ?>
									</div>

									<?php if ($templateType): ?>
										<?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
									<?php endif; ?>

									<?php if ($showWishlist || $showCompare || $showCart): ?>
										<div class="show_addtocart">
											<?php if ($showCart): ?>
												<div class="actions-primary">
													<?php if ($_item->isSaleable()): ?>
														<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
															<a class="add_to_cartbtn" href="javascript:;" data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
																<?= $block->escapeHtml(__('Add to Cart')) ?>
															</a>
														<?php else: ?>
															<?php
																$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
															?>
															<a class="add_to_cartbtn" href="javascript:;" data-post='<?= /* @noEscape */ $postData ?>' title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
																<?= $block->escapeHtml(__('Add to Cart')) ?>
															</a>
														<?php endif; ?>
													<?php else: ?>
														<?php if ($_item->getIsSalable()): ?>
															<div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
														<?php else: ?>
															<div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
														<?php endif; ?>
													<?php endif; ?>
												</div>
											<?php endif; ?>
											<?php if ($showWishlist || $showCompare): ?>
												<div class="actions-secondary" data-role="add-to-links">
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
														<a href="#"
														   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
															<span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
														</a>
													<?php endif; ?>
													<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
														<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
														<a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
															<span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
														</a>
													<?php endif; ?>
												</div>
											<?php endif; ?>
										</div>
									<?php endif; ?>
								</figcaption>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
</div>
<?php endif;?>
