<?php
$featuredCategories = $this->getFeaturedCategories();
?>
<div class="featured_list">
	<div class="container">
	  <h3><?php echo $this->getData('blocktitle'); ?></h3>  
		<ul>
		<?php foreach($featuredCategories as $featuredCategory): ?>
			<li>
				<div class="featured_outer">
					<a href="<?php echo $featuredCategory->getUrl(); ?>">
						<figure><img src="<?php echo $featuredCategory->getImageUrl(); ?>"> </figure>
						<figcaption><h4><?php echo $featuredCategory->getName(); ?></h4></figcaption>
					</a>
				</div>
			</li>
		<?php endforeach; ?>
		</ul>
	</div> 
</div>