<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<div class="responive_logo">
	<a href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
		<img src="<?php echo $this->getViewFileUrl('images/mobile_logo.png'); ?>"
			 title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
			 alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
			 <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
			 <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
		/>
	</a>
</div>

