<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="newsletter_outer">
    <div class="container">
		<h4><?= $block->escapeHtml(__('Newsletter')) ?></h4>
		<p><?= $block->escapeHtml(__('Subscribe to receive coupons and gift cards')) ?></p>
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
			
			<input name="email" type="email" id="newsletter" class="input_filed"
				placeholder="<?= $block->escapeHtml(__('Email address')) ?>"
				data-validate="{required:true, 'validate-email':true}"/>
			<input class="subc_btn" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit" value="<?= $block->escapeHtml(__('Subscribe')) ?>">
        </form>
    </div>
</div>
