<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<div class="header_search">
	<form class="form minisearch" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
		<input id="search"
		   data-mage-init='{"quickSearch":{
				"formSelector":"#search_mini_form",
				"url":"<?= /* @escapeNotVerified */ $helper->getSuggestUrl()?>",
				"destinationSelector":"#search_autocomplete"}
		   }'
		   type="text"
		   name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
		   value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
		   placeholder="<?= /* @escapeNotVerified */ __('Search entire store here...') ?>"
		   class="search-input"
		   maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
		   role="combobox"
		   aria-haspopup="false"
		   aria-autocomplete="both"
		   autocomplete="off"/>
		<button type="submit" class="submit"></button>
	</form>
</div>
