<?php
$helper = $this->helper('Cluedy\Mhlatk\Helper\Data');
/*
?>
<section>
	<div class="featured_list">
		<div class="container">
		  <h3>featured categories</h3>  
			<ul>
			<?php foreach($featuredCategories as $featuredCategory): ?>
				<li>
					<div class="featured_outer">
						<a href="<?php echo $featuredCategory->getUrl(); ?>">
							<figure><img src="<?php echo $featuredCategory->getImageUrl(); ?>"> </figure>
							<figcaption><h4><?php echo $featuredCategory->getName(); ?></h4></figcaption>
						</a>
					</div>
				</li>
			<?php endforeach; ?>
			</ul>
		</div> 
	</div>
	
	<?php if($topBanner): ?>
	<div class="add_section">
		<div class="container">
			<img class="dsktop_only" src="<?php echo $topBanner->getImageUrl(); ?>">
			<img class="mobile_only" src="<?php echo $topBanner->getMobileImageUrl(); ?>">
		
		</div>
	 </div>
	 <?php endif; ?>
	 
	 <div class="product_list_home best_elec">
		<div class="container">
			<h3>best of electronics</h3> 
			<ul class="best_elec_slider">
			
			<li class="new_arrival">
				 <div class="product_list_wrap">
			   <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a>                          
					 </figure>
				<figcaption>
					<h5><a href="#">Romoss 20000mAh Power Bank</a></h5> 
					<div class="product_price">
					<div class="price_trough">Aed 250.00</div>
					<div class="price_original">Aed 125.00</div>
						<a href="#" class="mob_addtocart"></a>
					</div>
					<div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Baseus Rotation Type Universial Charger</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 67.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li class="slash_sale">
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Fitbit Versa Lite Edition</a></h5> 
					<div class="product_price">
					<div class="price_trough">Aed 250.00</div>
					<div class="price_original">Aed 125.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Anker 5-Port 60W USB Wall Charger</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 185.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Baseus Bluetooth Headphone</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 350.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Ldnio 6 USB And 3 Port Plug</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 117.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
		   </ul>
		</div>
	 </div>
	  <div class="product_list_home mobile_acces">
	   <div class="container">
		 <h3>best of mobile accessories</h3> 
		   <ul>
			 <li class="new_arrival">
				 <div class="product_list_wrap">
			   <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a>                          
					 </figure>
				<figcaption>
					<h5><a href="#">Romoss 20000mAh Power Bank</a></h5> 
					<div class="product_price">
					<div class="price_trough">Aed 250.00</div>
					<div class="price_original">Aed 125.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					<div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Baseus Rotation Type Universial Charger</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 67.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li class="slash_sale">
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Fitbit Versa Lite Edition</a></h5> 
					<div class="product_price">
					<div class="price_trough">Aed 250.00</div>
					<div class="price_original">Aed 125.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Anker 5-Port 60W USB Wall Charger</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 185.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Baseus Bluetooth Headphone</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 350.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Ldnio 6 USB And 3 Port Plug</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 117.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
		   </ul>
		</div>
	 </div>
	 <!-- mobile only start-->
	 <div class="mob_only_process">
	 <div class="process_wrap">
			   <div class="process_img"><img src="<?php echo $this->getViewFileUrl('images/delivery_icon.png'); ?>"> </div>
			   <div class="process_content"><h4>fast &amp; free* delivery</h4><p>Within 24 Hours of Order Confirmation</p></div>
			   </div>
		 </div>
	 <!-- mobile only end-->
	 <div class="our_process">
	   <div class="container">
		 <ul>
		   <li>
			 <div class="process_wrap">
			   <div class="process_img"><img src="<?php echo $this->getViewFileUrl('images/delivery_icon.png'); ?>"> </div>
			   <div class="process_content"><h4>fast &amp; free* delivery</h4><p>Within 24 Hours of Order Confirmation</p></div>
			   </div>
			 </li>   
				<li>
			 <div class="process_wrap">
			   <div class="process_img"><img src="<?php echo $this->getViewFileUrl('images/return_icon.png'); ?>"> </div>
			   <div class="process_content"><h4>Easy Returns</h4><p>Free Return on Eligible Items So<br> You Can Shopping Comfortably</p></div>
			   </div>
			 </li> 
				<li>
			 <div class="process_wrap">
			   <div class="process_img"><img src="<?php echo $this->getViewFileUrl('images/cod_icon.png'); ?>"> </div>
			   <div class="process_content"><h4>cash on delivery</h4><p>You Can Pay Cash on Delivery<br> Without Extra Fees</p></div>
			   </div>
			 </li> 
		   </ul>
		 </div>
	 </div>
	 <div class="product_list_home gadgets_life">
	   <div class="container">
		 <h3>best of gadgets &amp; lifestyle</h3> 
		   <ul>
			 <li class="new_arrival">
				 <div class="product_list_wrap">
			   <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a>                          
					 </figure>
				<figcaption>
					<h5><a href="#">Romoss 20000mAh Power Bank</a></h5> 
					<div class="product_price">
					<div class="price_trough">Aed 250.00</div>
					<div class="price_original">Aed 125.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					<div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Baseus Rotation Type Universial Charger</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 67.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li class="slash_sale">
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Fitbit Versa Lite Edition</a></h5> 
					<div class="product_price">
					<div class="price_trough">Aed 250.00</div>
					<div class="price_original">Aed 125.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Anker 5-Port 60W USB Wall Charger</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 185.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Baseus Bluetooth Headphone</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 350.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Ldnio 6 USB And 3 Port Plug</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 117.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
		   </ul>
		</div>
	 </div>
	  <!-- mobile only start-->
	 <div class="mob_only_process">
	 <div class="process_wrap">
			   <div class="process_img"><img src="<?php echo $this->getViewFileUrl('images/return_icon.png'); ?>"> </div>
			   <div class="process_content"><h4>Easy Returns</h4><p>Free Return on Eligible Items So<br> You Can Shopping Comfortably</p></div>
			   </div>
		 </div>
	 <!-- mobile only end-->
	 <div class="product_list_home home_kitchen">
	   <div class="container">
		 <h3>best of HOME &amp; KITCHEN</h3> 
		   <ul>
			 <li class="new_arrival">
				 <div class="product_list_wrap">
			   <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a>                          
					 </figure>
				<figcaption>
					<h5><a href="#">Romoss 20000mAh Power Bank</a></h5> 
					<div class="product_price">
					<div class="price_trough">Aed 250.00</div>
					<div class="price_original">Aed 125.00</div>
						 <a href="#" class="mob_addtocart"></a>
					</div>
					<div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Baseus Rotation Type Universial Charger</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 67.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li class="slash_sale">
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Fitbit Versa Lite Edition</a></h5> 
					<div class="product_price">
					<div class="price_trough">Aed 250.00</div>
					<div class="price_original">Aed 125.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Anker 5-Port 60W USB Wall Charger</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 185.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Baseus Bluetooth Headphone</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 350.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Ldnio 6 USB And 3 Port Plug</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 117.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
		   </ul>
		</div>
	 </div>
	 
	<?php if($bottomBanner): ?>
	<div class="ramadan_add">
		<div class="container">
			<img class="dsktop_only" src="<?php echo $bottomBanner->getImageUrl(); ?>">
			<img class="mobile_only" src="<?php echo $bottomBanner->getMobileImageUrl(); ?>">
		</div>
	</div>
	<?php endif; ?>
	 
	
	   <div class="product_list_home wall_bag">
	   <div class="container">
		 <h3>best of wallets &amp; bags</h3> 
		   <ul>
			 <li class="new_arrival">
				 <div class="product_list_wrap">
			   <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a>                          
					 </figure>
				<figcaption>
					<h5><a href="#">Romoss 20000mAh Power Bank</a></h5> 
					<div class="product_price">
					<div class="price_trough">Aed 250.00</div>
					<div class="price_original">Aed 125.00</div>
					</div>
					<div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Baseus Rotation Type Universial Charger</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 67.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li class="slash_sale">
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Fitbit Versa Lite Edition</a></h5> 
					<div class="product_price">
					<div class="price_trough">Aed 250.00</div>
					<div class="price_original">Aed 125.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Anker 5-Port 60W USB Wall Charger</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 185.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Baseus Bluetooth Headphone</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 350.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Ldnio 6 USB And 3 Port Plug</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 117.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
		   </ul>
		</div>
	 </div>
	   <!-- mobile only start-->
	 <div class="mob_only_process">
	 <div class="process_wrap">
			   <div class="process_img"><img src="<?php echo $this->getViewFileUrl('images/cod_icon.png'); ?>"> </div>
			   <div class="process_content"><h4>cash on delivery</h4><p>You Can Pay Cash on Delivery
Without Extra Fees</p></div>
			   </div>
		 </div>
	 <!-- mobile only end-->
	 <div class="product_list_home health_beaty">
	   <div class="container">
		 <h3>best of health &amp; beauty</h3> 
		   <ul>
			 <li class="new_arrival">
				 <div class="product_list_wrap">
			   <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a>                          
					 </figure>
				<figcaption>
					<h5><a href="#">Romoss 20000mAh Power Bank</a></h5> 
					<div class="product_price">
					<div class="price_trough">Aed 250.00</div>
					<div class="price_original">Aed 125.00</div>
					</div>
					<div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Baseus Rotation Type Universial Charger</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 67.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li class="slash_sale">
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Fitbit Versa Lite Edition</a></h5> 
					<div class="product_price">
					<div class="price_trough">Aed 250.00</div>
					<div class="price_original">Aed 125.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Anker 5-Port 60W USB Wall Charger</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 185.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Baseus Bluetooth Headphone</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 350.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
				  <li>
				 <div class="product_list_wrap">
					 <figure><a href="#"><img src="<?php echo $this->getViewFileUrl('images/be1.png'); ?>"></a></figure>
				<figcaption>
					<h5><a href="#">Ldnio 6 USB And 3 Port Plug</a></h5> 
					<div class="product_price"> 
					<div class="price_original">Aed 117.00</div>
					</div>
					 <div class="show_addtocart">
					 <a href="#" class="add_to_cartbtn">Add To Cart</a>
					</div>
					</figcaption>
					 </div>
			   </li>
		   </ul>
		</div>
	 </div>
	 
 </section>
 */ ?>