<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer_copy">
	<a class="whatup" href="#"><img src="<?php echo $this->getViewFileUrl('images/whatup_icon.png'); ?>"> </a>
	<div class="container">
		<div class="ftr_copy">
			<p><?= /* @escapeNotVerified */ $block->getCopyright() ?></p>
		</div>
		<div class="ftr_right">
			<img src="<?php echo $this->getViewFileUrl('images/ftr_right.png'); ?>">
		</div>
	</div>    
</div>
