<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav data-action="navigation">
	<div class="container">
		<div class="nav_left">
			<img src="<?php echo $this->getViewFileUrl('images/cat_icon.png'); ?>"> 
			<ul class="cat_mainer">
				<li>
					<a class="category_main">CATEGORIES</a>
					<ul class="catry_menu">
						<?= /* @escapeNotVerified */ $_menu ?>
						<?= /* @escapeNotVerified */ $block->getChildHtml() ?>
					</ul>
				</li>
			</ul>
        </div>
		<div class="nav_middle">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_main_menu')->toHtml(); ?>
		</div>
		<div class="nav_right">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_right_menu')->toHtml(); ?>
		</div>
	</div>    
</nav>
