<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
	<?php if ($block->shouldRenderQuantity()): ?>
	<div class="ecomm_product_quantity">
		<div class="ecomm_select">
			<a href="javascript://" class="button">-</a>
			<input type="number"
				   name="qty"
				   id="qty"
				   value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
				   title="<?= /* @escapeNotVerified */ __('Qty') ?>"
				   class="quantity_count"
				   data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
				   />
			<a href="javascript://" class="button">+</a>
		</div>
	</div>
	<?php endif; ?>
	<div class="add_prodcut">
		<input type="submit"
				title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
				class="add_to_button"
				id="product-addtocart-button"
				value ="<?= $buttonTitle ?>"/>
		<?= $block->getChildHtml('', true) ?>
	</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
