<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>

<div class="header_crt_top">
	<div class="hrt_carts">
		<ul class="user_iconer">
			<li>
				<a href="">
					<img alt="" src="<?php echo $this->getViewFileUrl('images/user_icon.png'); ?>">
					<i aria-hidden="true" class="fa fa-angle-down"></i>
				</a>
				<div class="dashboard_popup">
					<ul class="login_list">
						<li><a href="#">Sign In</a> </li><li>&nbsp;|</li>
						<li><a href="#">Join</a> </li>
					</ul>
					<ul class="dashboard_list"> 
						<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/dash_user.png'); ?>"> My Account</a></li>
						<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/dash_hist.png'); ?>"> Order History</a></li> 
						<li><a href="#"><img src="<?php echo $this->getViewFileUrl('images/dash_cont.png'); ?>"> Contact</a></li> 
					</ul>
				</div>
			</li>
		</ul>
		<div data-block="minicart" class="minicart-wrapper cart-count">
			<p>
				<a class="ecomm_my_cart_link action" href="<?= /* @escapeNotVerified */ $block->getShoppingCartUrl() ?>"
				   data-bind="scope: 'minicart_content'">
					<img src="<?php echo $this->getViewFileUrl('images/cart_icon.png'); ?>">
					<sup class="counter qty empty"
						  data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
						<span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
						<span class="counter-label">
						<!-- ko if: getCartParam('summary_count') -->
							<!-- ko text: getCartParam('summary_count') --><!-- /ko -->
							<!-- ko i18n: 'items' --><!-- /ko -->
						<!-- /ko -->
						</span>
					</sup>
				</a>
			</p>
			<?php if ($block->getIsNeedToDisplaySideBar()): ?>
				<div class="block block-minicart"
					 data-role="dropdownDialog"
					 data-mage-init='{"dropdownDialog":{
						"appendTo":"[data-block=minicart]",
						"triggerTarget":".showcart",
						"timeout": "2000",
						"closeOnMouseLeave": false,
						"closeOnEscape": true,
						"triggerClass":"active",
						"parentClass":"active",
						"buttons":[]}}'>
					<div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
						<!-- ko template: getTemplate() --><!-- /ko -->
					</div>
					<?= $block->getChildHtml('minicart.addons') ?>
				</div>
			<?php else: ?>
				<script>
					require(['jquery'], function ($) {
						$('a.action.showcart').click(function() {
							$(document.body).trigger('processStart');
						});
					});
				</script>
			<?php endif ?>
			<script>
				window.checkout = <?= /* @escapeNotVerified */ $block->getSerializedConfig() ?>;
			</script>
			<script type="text/x-magento-init">
			{
				"[data-block='minicart']": {
					"Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
				},
				"*": {
					"Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
				}
			}
			</script>
		</div>
	</div>
</div>



